### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by player1321** [PathologyDataScience/CrowdsourcingDataset-Amgadetal2019#17]
Hello,

I ran `python download_crowdsource_dataset.py`  but got 502 Bad Gateway:
```
girder_client.HttpError: HTTP error 502: POST https://demo.kitware.com/histomicstk/api/v1/api_key/token?key=n0Kp1ez8YOnOiWNoACryzeBlIzbUDW3iOD2DmPLI
Response text: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```
Is the data not available now?

**Comment by mostafajahanifar** [comment]
Hi, 
I have the same issue here. It seems that the histomicstk is not working at the moment. But it's odd  that it has been down at least for three days now. @kheffah  can you please confirm if this is the issue? Thanks,

**Comment by kheffah** [comment]
Dear @player1321 and @mostafajahanifar Thank you for raising this issue. It seems the Kitware server has been down a few times lately. To avoid disruptions, now the dataset can also be downloaded directly at 0.25 MPP, using [this direct link](https://drive.google.com/drive/folders/1zqbdkQF8i5cEmZOGmbdQm-EP8dRYtvss?usp=sharing).

**Comment by mostafajahanifar** [comment]
> Dear @player1321 and @mostafajahanifar Thank you for raising this issue. It seems the Kitware server has been down a few times lately. To avoid disruptions, now the dataset can also be downloaded directly at 0.25 MPP, using [this direct link](https://drive.google.com/drive/folders/1zqbdkQF8i5cEmZOGmbdQm-EP8dRYtvss?usp=sharing).

Wonderful. Thanks for the prompt reply Mohamed.

**Comment by mostafajahanifar** [comment]
Sorry @kheffah, I understand you have closed this issue, but can you kindly provide the information on the train/validation/test splits as well.

**Comment by kheffah** [comment]
@mostafajahanifar You are more than welcome. I like to separate training and testing sets by hospital for a better reflection of the external generalization of the model. The train/test split used for the model in our paper is discussed [here](https://bcsegmentation.grand-challenge.org/Baseline/). Recently, I've switched to internal-external cross-validation, where the hospitals that constitute the testing set are switched around to provide some variance around the accuracy metric -- for example, see how we split the train-test sets for the NuCLS paper [here](https://nucls.grand-challenge.org/Baseline/). Note that some hospitals have more slides than others. In my recent projects, I make sure each fold has at least one "big" hospital, having at least 9 slides. Note that the slide name encodes the hospital name, so the slide TCGA-**E2**-A14X-DX1, for example, comes from the hospital E2.

I hope this answers your question. Let me know if you need any clarifications.

**Comment by mostafajahanifar** [comment]
> @mostafajahanifar You are more than welcome. I like to separate training and testing sets by hospital for a better reflection of the external generalization of the model. The train/test split used for the model in our paper is discussed [here](https://bcsegmentation.grand-challenge.org/Baseline/). Recently, I've switched to internal-external cross-validation, where the hospitals that constitute the testing set are switched around to provide some variance around the accuracy metric -- for example, see how we split the train-test sets for the NuCLS paper [here](https://nucls.grand-challenge.org/Baseline/). Note that some hospitals have more slides than others. In my recent projects, I make sure each fold has at least one "big" hospital, having at least 9 slides. Note that the slide name encodes the hospital name, so the slide TCGA-**E2**-A14X-DX1, for example, comes from the hospital E2.
> 
> I hope this answers your question. Let me know if you need any clarifications.

Thank you very much @kheffah for your detailed explanations. I cannot agree more with the new internal-external cross-validation scheme that you are taking. However, for this particular purpose I want to compare my model performance with your baseline for which you directed me to the related information. Again, I appreciate your help.

**Comment by kheffah** [comment]
@mostafajahanifar You're more than welcome. Let me know if you need anything else.

**Comment by mostafajahanifar** [comment]
@player1321 and @kheffah , just to let you know, I have contacted the Kitware people and they have fixed the problem with the website. So, I guess it's problem free to use the code for dataset extraction now.

**Comment by kheffah** [comment]
@mostafajahanifar Thank you! That was very nice of you.
