### ISSUE TITLE
Download images for TCGA samples

### ISSUE THREAD

**Issue by hegu2692** [PathologyDataScience/CrowdsourcingDataset-Amgadetal2019#18]
Hello, Dr. kheffah, 
I want to download images from TCGA STAD and COAD cohorts for some analysis. By using this package, I can only download 151 samples. Can you help me with this? Thank you very much for your support.
Jian

**Comment by cooperlab** [comment]
Please consult the GDC for help with TCGA data https://portal.gdc.cancer.gov/.
